version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      #PMA_USER: root Remove line for production
      #PMA_PASSWORD: root Remove line for production
    depends_on:
      - redis-db-container
    ports:
      - "81:80"
    #restart: always
  db:
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - /home/ema/ged/mysql_data:/var/lib/mysql
  php:
    container_name: php
    build: ./php-fpm
    depends_on:
      - phpmyadmin
    ports:
      - "9001:9000"
    volumes:
      - /home/ema/ged/html:/var/www/html
      - ./logs/php/error.log:/var/log/php7/error.log
        #nginx:
        #container_name: nginx
        #build: ./nginx
        #ports:
        #- "80:80"
        #depends_on:
        #- php
        #volumes:
        #- ./logs/nginx:/var/log/nginx
      #- /Users/macbookpro/Projects/web:/var/www
  nodejs:
    container_name: nodejs
    build: ./nodejs
    #restart: always
    ports:
      - "3000:3000"
    depends_on:
      - apache
    volumes:
      - /home/ema/ged/html/gedmindef/realtime:/app
  redis-db-container:
    container_name: redis-db-container
    build: ./redis
    #restart: always
    depends_on:
      - db
    ports:
      - "6379:6379"
    volumes:
      - /home/ema/ged/redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3 # 6.8.4 out
    ports:
      - "9209:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.flood_stage=800mb
      - cluster.routing.allocation.disk.watermark.low=1800mb
      - cluster.routing.allocation.disk.watermark.high=1200mb
      - xpack.security.audit.enabled=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ELASTIC_PASSWORD=elastic
    volumes:
      - /home/ema/ged/elastic:/usr/share/elasticsearch/data
  elasticsearch-head:
    container_name: sb-elasticsearch-head
    depends_on:
      - elasticsearch
    image: tobias74/elasticsearch-head:6
    ports:
      - "9109:9100"
      #kibana:
      #depends_on:
      #- elasticsearch
      #image: "docker.elastic.co/kibana/kibana:6.8.18"
      #ports:
      #- "5601:5601"
      #environment:
      #- ELASTICSEARCH_URL=http://localhost:9209
      #- ELASTICSEARCH_USERNAME=elastic
      #- ELASTICSEARCH_PASSWORD=elastic
  apache:
    container_name: apache
    build: ./apache
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/apache:/var/log/apache2/apache
      - /home/ema/ged/html:/var/www/html

